- hosts: local
  connection: local
  become: yes
  become_user: root
  tasks:
    - name: Install git
      apt: pkg=git state=installed

    - name: Add repository for java 8
      apt_repository: repo='ppa:webupd8team/java' state=present

    - name: Agree to oracle license
      debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

    - name: Install java 8
      apt: name=oracle-java8-installer state=latest update-cache=yes force=yes

    - name: Register apt sources for sbt
      shell: echo "deb https://dl.bintray.com/sbt/debian /" > /etc/apt/sources.list.d/sbt.list

    - name: Add sbt key
      apt_key:
        keyserver: hkp://keyserver.ubuntu.com:80
        id: 2EE0EA64E40A89B84B2DF73499E82A75642AC823

    - name: Install sbt
      apt: name=sbt state=present update_cache=yes force=yes

    - name: Add docker's key
      apt_key:
        keyserver: hkp://p80.pool.sks-keyservers.net:80
        id: 58118E89F3A912897C070ADBF76221572C52609D

    - name: Add deb repo
      file: path=/etc/apt/sources.list.d/docker.list state=touch

    - name: Register apt sources for docker
      lineinfile: dest="/etc/apt/sources.list.d/docker.list" line="{{item}}"
      with_items:
      - "deb https://apt.dockerproject.org/repo ubuntu-trusty main"

    - name: Install docker-engine
      apt: name=docker-engine state=present update-cache=yes force=yes